[phases.install]
packageManager = "pnpm"
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
packageManager = "pnpm"
cmds = ["pnpm --filter '@repo/web' build"]

[start]
packageManager = "pnpm"
cmd = "npx serve -s apps/web/dist -l ${PORT:-3001}"
