[phases.install]
packageManager = "pnpm"
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
packageManager = "pnpm"
cmds = ["pnpm --filter '@repo/api' build"]

[start]
packageManager = "pnpm"
cmd = "pnpm --filter '@repo/api' start"
